from enum import Enum


class SignalType(str, Enum):
    NEW_DISCLOSURE = "NEW_DISCLOSURE"
    REMOVED_DISCLOSURE = "REMOVED_DISCLOSURE"
    SEMANTIC_DRIFT = "SEMANTIC_DRIFT"
    RISK_INCREASED = "RISK_INCREASED"
